name: Release x64

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@1.77.2
      with:
        targets: x86_64-pc-windows-msvc
    - run: cargo build --release --target x86_64-pc-windows-msvc
    - name: Zip artifact
      run: |
        Compress-Archive -Path "target/x86_64-pc-windows-msvc/release/startx.exe" -DestinationPath "startx-${{ github.ref_name }}-x64.zip"
    - uses: actions/upload-artifact@v4
      with:
        name: startx-x64
        path: startx-${{ github.ref_name }}-x64.zip

  release:
    needs: build
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/download-artifact@v4
      with:
        pattern: startx-*
        merge-multiple: true
    - name: Create Release
      run: |
        gh release create $env:GITHUB_REF_NAME *.zip --title $env:GITHUB_REF_NAME --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}
