name: Release

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write


jobs:
  release:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: dtolnay/rust-toolchain@stable
    - run: cargo build --release
    - name: Create Release
      run: |
        gh release create $env:GITHUB_REF_NAME target/x86_64-pc-windows-msvc/startx.exe --title $env:GITHUB_REF_NAME --generate-notes
      env:
        GH_TOKEN: ${{ github.token }}

